import { Injectable } from '@angular/core';
import { WordListComponent } from './lists/word-list.component';
import { AddWord } from './add-word';


// interface wordList {
//   [key: string]: object
// }

@Injectable({ providedIn: 'root' })
export class WordService {

  private lists :any = [];
  

  constructor() {
    this.lists['one'] = [
      { prompt: 'tower', answer: 'bell' },
      { prompt: 'sea', answer: 'tide' },
      { prompt: 'newspaper', answer: 'interview' },
      { prompt: 'sonata', answer: 'joy' },
      { prompt: 'banner', answer: 'camp' },
      { prompt: 'tendency', answer: 'increment' },
      { prompt: 'mother', answer: 'child' },
      { prompt: 'insect', answer: 'caterpillar' },
      { prompt: 'river', answer: 'ship' },
      { prompt: 'coast', answer: 'beach' },
      { prompt: 'gun', answer: 'bullet' },
      { prompt: 'blacksmith', answer: 'metal' },
      { prompt: 'home', answer: 'room' },
      { prompt: 'building', answer: 'hall' },
      { prompt: 'rain', answer: 'flood' },
      { prompt: 'avenue', answer: 'tree' },
      { prompt: 'decency', answer: 'truth' },
      { prompt: 'decree', answer: 'decision' },
      { prompt: 'diamond', answer: 'hardness' },
      { prompt: 'result', answer: 'effect' },
      { prompt: 'occupation', answer: 'doctor' },
      { prompt: 'book', answer: 'story' },
      { prompt: 'attack', answer: 'operation' },
      { prompt: 'cat', answer: 'soul' },
      { prompt: 'doll', answer: 'cradle' },
      { prompt: 'episode', answer: 'happiness' },
      { prompt: 'railroad', answer: 'steam' },
      { prompt: 'kitchen', answer: 'pot' },
      { prompt: 'countryside', answer: 'swamp' },
      { prompt: 'musician', answer: 'pianist' },
      { prompt: 'industry', answer: 'factory' },
      { prompt: 'clothing', answer: 'scarf' },
      { prompt: 'car', answer: 'headlight' },
      { prompt: 'gale', answer: 'wind' },
      { prompt: 'bouquet', answer: 'blossom' },
      { prompt: 'bottle', answer: 'toast' },
      { prompt: 'group', answer: 'person' },
      { prompt: 'crisis', answer: 'emergency' },
      { prompt: 'girl', answer: 'engagement' },
      { prompt: 'harbor', answer: 'crane' }
    ];

    this.lists['three'] = [
      { prompt: 'fire', answer: 'smoke' },
      { prompt: 'animal', answer: 'fox' },
      { prompt: 'road', answer: 'car' },
      { prompt: 'weaver', answer: 'troubles' },
      { prompt: 'flakes', answer: 'rescue' },
      { prompt: 'rein', answer: 'turn' },
      { prompt: 'mission', answer: 'messenger' },
      { prompt: 'furniture', answer: 'chair' },
      { prompt: 'body', answer: 'blood' },
      { prompt: 'army', answer: 'admiral' },
      { prompt: 'bird', answer: 'lark' },
      { prompt: 'celebration', answer: 'alcohol' },
      { prompt: 'grain', answer: 'oats' },
      { prompt: 'joint', answer: 'knuckle' },
      { prompt: 'artist', answer: 'painting' },
      { prompt: 'statement', answer: 'doubt' },
      { prompt: 'revolt', answer: 'policeman' },
      { prompt: 'alliance', answer: 'betrayal' },
      { prompt: 'event', answer: 'incident' },
      { prompt: 'factory', answer: 'foreman' },
      { prompt: 'plant', answer: 'leaf' },
      { prompt: 'tenant', answer: 'rent' },
      { prompt: 'commercial', answer: 'candy' },
      { prompt: 'giant', answer: 'club' },
      { prompt: 'trip', answer: 'map' },
      { prompt: 'mountain', answer: 'boulder' },
      { prompt: 'ruler', answer: 'palace' },
      { prompt: 'play', answer: 'drama' },
      { prompt: 'illness', answer: 'doctor' },
      { prompt: 'church', answer: 'heaven' },
      { prompt: 'infection', answer: 'bacteria' },
      { prompt: 'university', answer: 'semester' },
      { prompt: 'underworld', answer: 'crime' },
      { prompt: 'instrument', answer: 'bagpipes' },
      { prompt: 'glacier', answer: 'avalanche' },
      { prompt: 'idea', answer: 'proverb' },
      { prompt: 'faith', answer: 'renouncement' },
      { prompt: 'theory', answer: 'concept' },
      { prompt: 'authority', answer: 'state' },
      { prompt: 'fir', answer: 'needle' }
    ];
    
    this.lists['five'] = [
      { prompt: 'power', answer: 'ruler' },
      { prompt: 'butterfly', answer: 'bloom' },
      { prompt: 'dream', answer: 'reality' },
      { prompt: 'language', answer: 'acoustic' },
      { prompt: 'examiner', answer: 'failure' },
      { prompt: 'coach', answer: 'horse' },
      { prompt: 'animal', answer: 'frog' },
      { prompt: 'demand', answer: 'difficulty' },
      { prompt: 'question', answer: 'objection' },
      { prompt: 'grass', answer: 'cattle' },
      { prompt: 'decency', answer: 'custom' },
      { prompt: 'welcoming', answer: 'kindness' },
      { prompt: 'criticism', answer: 'doubt' },
      { prompt: 'friend', answer: 'trust' },
      { prompt: 'pardon', answer: 'mercy' },
      { prompt: 'loss', answer: 'removal' },
      { prompt: 'destiny', answer: 'irony' },
      { prompt: 'mountain', answer: 'cabin' },
      { prompt: 'ghost', answer: 'appearance' },
      { prompt: 'barrel', answer: 'basement' },
      { prompt: 'marriage', answer: 'engagement' },
      { prompt: 'swell', answer: 'steamship' },
      { prompt: 'discipline', answer: 'obedience' },
      { prompt: 'painter', answer: 'pianist' },
      { prompt: 'analysis', answer: 'result' },
      { prompt: 'veiling', answer: 'headscarf' },
      { prompt: 'nephew', answer: 'grandmother' },
      { prompt: 'redemption', answer: 'heaven' },
      { prompt: 'growth', answer: 'progress' },
      { prompt: 'look', answer: 'perspective' },
      { prompt: 'twilight', answer: 'dawn' },
      { prompt: 'illusion', answer: 'perception' },
      { prompt: 'comedy', answer: 'drama' },
      { prompt: 'clock', answer: 'church' },
      { prompt: 'bungalow', answer: 'settlement' },
      { prompt: 'firmness', answer: 'strength' },
      { prompt: 'criterion', answer: 'selection' },
      { prompt: 'valley', answer: 'meadow' },
      { prompt: 'skin', answer: 'blood' },
      { prompt: 'garden', answer: 'flowerbed' }
    ];

    this.lists['osa-one'] = [
      { prompt: 'doll', answer: 'cradle' },
      { prompt: 'building', answer: 'hall' },
      { prompt: 'gale', answer: 'wind' },
      { prompt: 'sea', answer: 'tide' },
      { prompt: 'episode', answer: 'happiness' },
      { prompt: 'harbor', answer: 'crane' },
      { prompt: 'tower', answer: 'bell' },
      { prompt: 'attack', answer: 'operation' },
      { prompt: 'result', answer: 'effect' },
      { prompt: 'school', answer: 'blackboard' },
      { prompt: 'occupation', answer: 'doctor' },
      { prompt: 'car', answer: 'headlight' },
      { prompt: 'garden', answer: 'flowerbed' },
      { prompt: 'gun', answer: 'bullet' },
      { prompt: 'mother', answer: 'child' },
      { prompt: 'coast', answer: 'beach' },
      { prompt: 'kitchen', answer: 'pot' },
      { prompt: 'musician', answer: 'pianist' },
      { prompt: 'avenue', answer: 'tree' },
      { prompt: 'group', answer: 'person' },
      { prompt: 'girl', answer: 'admiral' },
      { prompt: 'decency', answer: 'turn' },
      { prompt: 'diamond', answer: 'troubles' },
      { prompt: 'crisis', answer: 'frog' },
      { prompt: 'railroad', answer: 'proverb' },
      { prompt: 'insect', answer: 'painting' },
      { prompt: 'rain', answer: 'foreman' },
      { prompt: 'bottle', answer: 'fox' },
      { prompt: 'cat', answer: 'bacteria' },
      { prompt: 'blacksmith', answer: 'knuckle' },
      { prompt: 'industry', answer: 'doubt' },
      { prompt: 'book', answer: 'drama' },
      { prompt: 'river', answer: 'policeman' },
      { prompt: 'tendency', answer: 'needle' },
      { prompt: 'bouquet', answer: 'semester' },
      { prompt: 'countryside', answer: 'renouncement' },
      { prompt: 'decree', answer: 'palace' },
      { prompt: 'prison', answer: 'concept' },
      { prompt: 'newspaper', answer: 'incident' },
      { prompt: 'banner', answer: 'oats' }
    ];
    

    this.lists['osa-two'] = [
      { prompt: 'plant', answer: 'leaf' },
      { prompt: 'alliance', answer: 'betrayal' },
      { prompt: 'trip', answer: 'map' },
      { prompt: 'celebration', answer: 'alcohol' },
      { prompt: 'glacier', answer: 'avalanche' },
      { prompt: 'rider', answer: 'switch' },
      { prompt: 'church', answer: 'heaven' },
      { prompt: 'bird', answer: 'lark' },
      { prompt: 'fire', answer: 'smoke' },
      { prompt: 'friend', answer: 'loyalty' },
      { prompt: 'authority', answer: 'state' },
      { prompt: 'body', answer: 'blood' },
      { prompt: 'furniture', answer: 'chair' },
      { prompt: 'instrument', answer: 'bagpipes' },
      { prompt: 'mission', answer: 'messenger' },
      { prompt: 'giant', answer: 'club' },
      { prompt: 'commercial', answer: 'candy' },
      { prompt: 'illness', answer: 'doctor' },
      { prompt: 'mountain', answer: 'boulder' },
      { prompt: 'road', answer: 'car' },
      { prompt: 'weaver', answer: 'increment' },
      { prompt: 'grain', answer: 'emergency' },
      { prompt: 'revolt', answer: 'soul' },
      { prompt: 'statement', answer: 'factory' },
      { prompt: 'army', answer: 'caterpillar' },
      { prompt: 'rein', answer: 'metal' },
      { prompt: 'event', answer: 'toast' },
      { prompt: 'theory', answer: 'steam' },
      { prompt: 'fir', answer: 'camp' },
      { prompt: 'artist', answer: 'story' },
      { prompt: 'infection', answer: 'flood' },
      { prompt: 'factory', answer: 'blossom' },
      { prompt: 'university', answer: 'hardness' },
      { prompt: 'ruler', answer: 'engagement' },
      { prompt: 'animal', answer: 'interview' },
      { prompt: 'idea', answer: 'gangster' },
      { prompt: 'joint', answer: 'truth' },
      { prompt: 'faith', answer: 'swamp' },
      { prompt: 'play', answer: 'ship' },
      { prompt: 'reptile', answer: 'decision' }
    ];    

    this.lists['one-esp'] = [
      { prompt: 'torre', answer: 'campana' },
      { prompt: 'mar', answer: 'marea' },
      { prompt: 'periódico', answer: 'entrevista' },
      { prompt: 'sonata', answer: 'alegría' },
      { prompt: 'banner', answer: 'campamento' },
      { prompt: 'tendencia', answer: 'incremento' },
      { prompt: 'madre', answer: 'niño' },
      { prompt: 'insecto', answer: 'oruga' },
      { prompt: 'río', answer: 'barco' },
      { prompt: 'costa', answer: 'playa' },
      { prompt: 'pistola', answer: 'bala' },
      { prompt: 'herrero', answer: 'metal' },
      { prompt: 'casa', answer: 'habitación' },
      { prompt: 'edificio', answer: 'sala' },
      { prompt: 'lluvia', answer: 'inundación' },
      { prompt: 'avenida', answer: 'árbol' },
      { prompt: 'decencia', answer: 'verdad' },
      { prompt: 'decreto', answer: 'decisión' },
      { prompt: 'diamante', answer: 'dureza' },
      { prompt: 'resultado', answer: 'efecto' },
      { prompt: 'ocupación', answer: 'médico' },
      { prompt: 'historia de libro' },
      { prompt: 'ataque', answer: 'operación' },
      { prompt: 'gato', answer: 'alma' },
      { prompt: 'muñeca', answer: 'cuna' },
      { prompt: 'episodio', answer: 'felicidad' },
      { prompt: 'ferrocarril', answer: 'vapor' },
      { prompt: 'cocina', answer: 'olla' },
      { prompt: 'campo', answer: 'pantano' },
      { prompt: 'músico', answer: 'pianista' },
      { prompt: 'industria', answer: 'fábrica' },
      { prompt: 'ropa', answer: 'bufanda' },
      { prompt: 'coche', answer: 'faro' },
      { prompt: 'vendaval', answer: 'viento' },
      { prompt: 'ramo', answer: 'flor' },
      { prompt: 'botella', answer: 'tostada' },
      { prompt: 'grupo', answer: 'persona' },
      { prompt: 'crisis', answer: 'emergencia' },
      { prompt: 'chica', answer: 'compromiso' },
      { prompt: 'puerto', answer: 'grúa' }
    ];
    
    this.lists['three-esp'] = [
      { prompt: 'fuego', answer: 'humo' },
      { prompt: 'animal', answer: 'zorro' },
      { prompt: 'carretera', answer: 'coche' },
      { prompt: 'tejedor', answer: 'problemas' },
      { prompt: 'copos', answer: 'rescate' },
      { prompt: 'rein', answer: 'girar' },
      { prompt: 'misión', answer: 'mensajero' },
      { prompt: 'muebles', answer: 'silla' },
      { prompt: 'cuerpo', answer: 'sangre' },
      { prompt: 'ejército', answer: 'almirante' },
      { prompt: 'pájaro', answer: 'alondra' },
      { prompt: 'celebración', answer: 'alcohol' },
      { prompt: 'grano', answer: 'avena' },
      { prompt: 'articulación', answer: 'nudillo' },
      { prompt: 'artista', answer: 'pintura' },
      { prompt: 'declaración', answer: 'duda' },
      { prompt: 'revuelta', answer: 'policía' },
      { prompt: 'alianza', answer: 'traición' },
      { prompt: 'evento', answer: 'incidente' },
      { prompt: 'fábrica', answer: 'capataz' },
      { prompt: 'planta', answer: 'hoja' },
      { prompt: 'inquilino', answer: 'alquiler' },
      { prompt: 'comercial', answer: 'dulces' },
      { prompt: 'gigante', answer: 'club' },
      { prompt: 'viaje', answer: 'mapa' },
      { prompt: 'montaña', answer: 'roca' },
      { prompt: 'gobernante', answer: 'palacio' },
      { prompt: 'jugar', answer: 'drama' },
      { prompt: 'enfermedad', answer: 'doctor' },
      { prompt: 'iglesia', answer: 'cielo' },
      { prompt: 'infección', answer: 'bacterias' },
      { prompt: 'universidad', answer: 'semestre' },
      { prompt: 'inframundo', answer: 'crimen' },
      { prompt: 'instrumento', answer: 'gaita' },
      { prompt: 'glaciar', answer: 'avalancha' },
      { prompt: 'idea', answer: 'proverbio' },
      { prompt: 'fe', answer: 'renuncia' },
      { prompt: 'teoría', answer: 'concepto' },
      { prompt: 'autoridad', answer: 'estado' },
      { prompt: 'abeto', answer: 'aguja' }
    ];
    
    this.lists['five-esp'] = [
      { prompt: 'poder', answer: 'gobernante' },
      { prompt: 'mariposa', answer: 'floración' },
      { prompt: 'sueño', answer: 'realidad' },
      { prompt: 'idioma', answer: 'acústica' },
      { prompt: 'examinador', answer: 'fracaso' },
      { prompt: 'entrenador', answer: 'caballo' },
      { prompt: 'animal', answer: 'rana' },
      { prompt: 'demanda', answer: 'dificultad' },
      { prompt: 'pregunta', answer: 'objeción' },
      { prompt: 'hierba', answer: 'ganado' },
      { prompt: 'decencia', answer: 'personalizado' },
      { prompt: 'bienvenida', answer: 'amabilidad' },
      { prompt: 'crítica', answer: 'duda' },
      { prompt: 'amigo', answer: 'confiar' },
      { prompt: 'perdón', answer: 'misericordia' },
      { prompt: 'pérdida', answer: 'eliminación' },
      { prompt: 'destino', answer: 'ironía' },
      { prompt: 'montaña', answer: 'cabaña' },
      { prompt: 'fantasma', answer: 'apariencia' },
      { prompt: 'barril', answer: 'sótano' },
      { prompt: 'matrimonio', answer: 'compromiso' },
      { prompt: 'oleaje', answer: 'barco de vapor' },
      { prompt: 'disciplina', answer: 'obediencia' },
      { prompt: 'pintor', answer: 'pianista' },
      { prompt: 'análisis', answer: 'resultado' },
      { prompt: 'velo', answer: 'pañuelo' },
      { prompt: 'sobrino', answer: 'abuela' },
      { prompt: 'redención', answer: 'cielo' },
      { prompt: 'crecimiento', answer: 'progreso' },
      { prompt: 'mirar', answer: 'perspectiva' },
      { prompt: 'crepúsculo', answer: 'amanecer' },
      { prompt: 'ilusión', answer: 'percepción' },
      { prompt: 'comedia', answer: 'drama' },
      { prompt: 'reloj', answer: 'iglesia' },
      { prompt: 'bungalow', answer: 'asentamiento' },
      { prompt: 'firmeza', answer: 'fuerza' },
      { prompt: 'criterio', answer: 'selección' },
      { prompt: 'valle', answer: 'prado' },
      { prompt: 'piel', answer: 'sangre' },
      { prompt: 'jardín', answer: 'floral' }
    ];
    
    this.lists['osa-one-esp'] = [
      { prompt: 'muñeca', answer: 'cuna' },
      { prompt: 'edificio', answer: 'sala' },
      { prompt: 'vendaval', answer: 'viento' },
      { prompt: 'mar', answer: 'marea' },
      { prompt: 'episodio', answer: 'felicidad' },
      { prompt: 'puerto', answer: 'grúa' },
      { prompt: 'torre', answer: 'campana' },
      { prompt: 'ataque', answer: 'operación' },
      { prompt: 'resultado', answer: 'efecto' },
      { prompt: 'escuela', answer: 'pizarra' },
      { prompt: 'ocupación', answer: 'doctor' },
      { prompt: 'coche', answer: 'faro' },
      { prompt: 'jardín', answer: 'macizo de flores' },
      { prompt: 'pistola', answer: 'bala' },
      { prompt: 'madre', answer: 'niño' },
      { prompt: 'costa', answer: 'playa' },
      { prompt: 'cocina', answer: 'olla' },
      { prompt: 'músico', answer: 'pianista' },
      { prompt: 'avenida', answer: 'árbol' },
      { prompt: 'grupo', answer: 'persona' },
      { prompt: 'niña', answer: 'almirante' },
      { prompt: 'decencia', answer: 'giro' },
      { prompt: 'diamante', answer: 'problemas' },
      { prompt: 'crisis', answer: 'rana' },
      { prompt: 'ferrocarril', answer: 'proverbio' },
      { prompt: 'insecto', answer: 'pintura' },
      { prompt: 'lluvia', answer: 'capataz' },
      { prompt: 'botella', answer: 'zorro' },
      { prompt: 'gato', answer: 'bacteria' },
      { prompt: 'herrero', answer: 'nudillo' },
      { prompt: 'industria', answer: 'duda' },
      { prompt: 'libro', answer: 'drama' },
      { prompt: 'río', answer: 'policía' },
      { prompt: 'tendencia', answer: 'aguja' },
      { prompt: 'ramo', answer: 'semestre' },
      { prompt: 'campo', answer: 'renuncia' },
      { prompt: 'decreto', answer: 'palacio' },
      { prompt: 'prisión', answer: 'concepto' },
      { prompt: 'periódico', answer: 'incidente' },
      { prompt: 'banner', answer: 'avena' }
    ];

    this.lists['osa-two-esp'] = [
      { prompt: 'planta', answer: 'hoja' },
      { prompt: 'alianza', answer: 'traición' },
      { prompt: 'viaje', answer: 'mapa' },
      { prompt: 'celebración', answer: 'alcohol' },
      { prompt: 'glaciar', answer: 'avalancha' },
      { prompt: 'jinete', answer: 'cambiar' },
      { prompt: 'iglesia', answer: 'cielo' },
      { prompt: 'pájaro', answer: 'alondra' },
      { prompt: 'fuego', answer: 'humo' },
      { prompt: 'amigo', answer: 'lealtad' },
      { prompt: 'autoridad', answer: 'estado' },
      { prompt: 'cuerpo', answer: 'sangre' },
      { prompt: 'muebles', answer: 'silla' },
      { prompt: 'instrumento', answer: 'gaita' },
      { prompt: 'misión', answer: 'mensajero' },
      { prompt: 'gigante', answer: 'club' },
      { prompt: 'comercial', answer: 'dulces' },
      { prompt: 'enfermedad', answer: 'doctor' },
      { prompt: 'montaña', answer: 'roca' },
      { prompt: 'carretera', answer: 'coche' },
      { prompt: 'tejedor', answer: 'incremento' },
      { prompt: 'grano', answer: 'emergencia' },
      { prompt: 'revuelta', answer: 'alma' },
      { prompt: 'declaración', answer: 'fábrica' },
      { prompt: 'ejército', answer: 'oruga' },
      { prompt: 'rienda', answer: 'metal' },
      { prompt: 'evento', answer: 'brindis' },
      { prompt: 'teoría', answer: 'vapor' },
      { prompt: 'abeto', answer: 'campamento' },
      { prompt: 'artista', answer: 'historia' },
      { prompt: 'infección', answer: 'inundación' },
      { prompt: 'fábrica', answer: 'flor' },
      { prompt: 'universidad', answer: 'dureza' },
      { prompt: 'gobernante', answer: 'compromiso' },
      { prompt: 'animal', answer: 'entrevista' },
      { prompt: 'idea', answer: 'gángster' },
      { prompt: 'conjunto', answer: 'verdad' },
      { prompt: 'fe', answer: 'pantano' },
      { prompt: 'jugar', answer: 'enviar' },
      { prompt: 'reptil', answer: 'decisión' }
    ];
  }

  getWordList(listName : any) {
    return this.lists[listName];
  }

  getWords(listName : any) {
    let listObject: AddWord[] = [];
    this.lists[listName].forEach((element: any) => {
      listObject.push(new AddWord(WordListComponent,element));
    });
    return listObject;
  }
}
